#=====================================================================
#                 CPUBench config file template
#=====================================================================
#   Usage: Copy this to a new name. eg:
#        cd $cpubench/config
#        cp config-template.ini test_xxx.ini
#
#   For more details, refer to docs/config.md.
#=====================================================================

#=========================Common Settings=============================
#           'common' means that all benchmarks are affected.
#=====================================================================
[common]
action = standard          # options: standard, build, run, clean
benchmarks = IntSingle     # Example: x264,gcc or lightgbm
arch = auto                # arch: auto, aarch64, x86_64, mips64el
tag = original
tune = extreme             # options: typical, extreme, both
# CPUBENCH-BOLT-RUNNER: Keep |jobs| in sync with cpubench-optimized.ini at all time.
jobs = 1                   # 1: single-core performance. 1+: Multi-Core Performance.
iterations = 3
verbose = 0                # options: 0(close), 1(open)
work_dir = work_dir        # Any directory with the write permission.
rebuild = 0                # options: 0(close), 1(open)
# taskset = 0-8,10,12-15   # Set the number of the bound CPU core.

#=======================Tester Descriptions===========================
test_sponsor = CSMantle    # Example: CPUBench
test_date =                # Example: 2021.01.01
manufacturer =             # Example: CPUBench

#=====================System Availability Dates=======================
software_available_time =  # Example: 2020.12.31
hardware_available_time =  # Example: 2020.12.31

#======================Compile Environment============================
ptrsize =                  # Example: 64-bits
compiler =                 # Example: gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

#=======================System information============================
machine_name =             # Example: Huawei 2288H V5
cpu_name =                 # Example: KunPeng 920
cpu_nominal_mhz =          # Example: 9999
cpu_max_mhz =              # Example: 9999
l1_cache =                 # Example: 64K
l2_cache =                 # Example: 512K
l3_cache =                 # Example: 49152K
os =                       # Example: Linux Malluma 4.14.0-115.el7a.0.1.aarch64
memory =                   # Example: 254G
hardware_others =          # Example: BIOS CPU Prefetching: Enable
software_others =          # Example: swapoff -a
license_id =               # Example: 0fada854365cacggbopspckl

#==========================Debug Options==============================
perf = 0                   # 0(close), 1(open). You are advised to set iterations to 1 when you enable it.
# You can customize the collection command and assign it a target name to distinguish it from other commands.
# eg. perf_strace = strace -o {output} -p {pid}
# For details, see config.md.
perf_timeout = 60          # Set the collection timeout.

#=========================Namespace Settings==========================
#      The items here take effect only for specified namespace.
#
# There are priorities between namespaces, for example:
#   [default] according to common sense, it has the lowest priority.
#   [IntConcurrent] priority is higher than [default] and takes effect for the benchmarks of this suite.
#   [int_x264] has the highest priority, but takes effect only for a specific benchmark.
#=====================================================================
[default]
lang_dir = /usr/bin
#LD_LIBRARY_PATH =

#==========================Compiler for C=============================
CC = ${lang_dir}/gcc
CC_VERSION = -v

# Compiler flags for compatibility with GCC 14 or higher:
# -Wno-incompatible-pointer-types: Suppress warnings about conversions between incompatible pointer types.
# -Wno-implicit-function-declaration: Suppress warnings about implicit function declarations.
# -Wno-implicit-int: Suppress warnings about implicit int type for return type or variable type.
CFLAGS = -O3 -Wno-incompatible-pointer-types -Wno-implicit-function-declaration -Wno-implicit-int

#==========================Compiler for C++===========================
CXX = ${lang_dir}/g++
CXX_VERSION = -v
CXXFLAGS = -O3             # Example: -fno-strict-aliasing -fgnu89-inline

#=============================LD Flags================================
CLD =                      # Example: ${CC}
CXXLD =                    # Example: ${CXX}
FLD =                      # Example: ${FC}
CLD_FLAGS =                # Example: -Wl,-Bsymbolic
CXXLD_FLAGS =              # Example: -Wl,-Bsymbolic
FLD_FLAGS =                # Example: -Wl,-Bsymbolic
LD_FLAGS = -Wl,-q          # Example: -Wl,-Bsymbolic

#=============================LIBS Flags==============================
LIBS =                     # Example: -lpthread
AR = ar
RANLIB = ranlib

#=========================Compiler for fortran========================
FC = ${lang_dir}/gfortran
FC_VERSION = -v
FFLAGS = -O3 -fallow-argument-mismatch -fallow-invalid-boz

#=============================JAVA Option=============================
java_options =             # Example: -XX:ParallelGCThreads=1
